snd-lx6464es-objs := lx6464es.o lx_core.o lxcommon.o
obj-$(CONFIG_SND_LX6464ES) += snd-lx6464es.o

snd-lxmadi-objs := lxmadi.o lx_core.o lxcommon.o
obj-$(CONFIG_SND_LXMADI) += snd-lxmadi.o

snd-lxip-objs := lxip.o lx_core.o lxcommon.o
obj-$(CONFIG_SND_LXIP) += snd-lxip.o